# Generated by Django 2.2.4 on 2019-08-09 22:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=200)),
                ('isin', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('index_isin', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('firm', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('Equity Hedge', 'Equity Hedge'), ('Event Driven', 'Event Driven'), ('Global Macro', 'Global Macro'), ('Relative Value', 'Relative Value')], max_length=200)),
                ('strategy', models.CharField(choices=[('Equity Long/Short', 'Equity Long/Short'), ('Equity Market Neutral', 'Equity Market Neutral'), ('Equity Long Bias', 'Equity Long Bias'), ('Activist', 'Activist'), ('Value-wth-catalyst', 'Value-with-catalyst'), ('ED Multi Strategy', 'ED Multi Strategy')], max_length=200)),
                ('flag_restricted', models.BooleanField(default=False)),
                ('flag_late_cutoff', models.BooleanField(default=False)),
                ('flag_units_trading', models.BooleanField(default=False)),
                ('terms_rank', models.PositiveSmallIntegerField(default=1)),
                ('terms_rank_amount', models.PositiveIntegerField()),
                ('terms_sub_notice', models.PositiveSmallIntegerField()),
                ('terms_sub_settlement', models.PositiveSmallIntegerField()),
                ('terms_sub_minimum', models.PositiveIntegerField()),
                ('terms_red_notice', models.PositiveSmallIntegerField()),
                ('terms_red_settlement', models.PositiveSmallIntegerField()),
                ('terms_cutoff_time', models.TimeField(default=datetime.time(17, 30))),
                ('terms_calendars', models.CharField(default='', max_length=500)),
                ('terms_man_fee', models.DecimalField(decimal_places=5, max_digits=6)),
                ('terms_perf_fee', models.DecimalField(decimal_places=5, max_digits=6)),
                ('terms_currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=200)),
                ('account_number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('guideline_shares_owned', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('guideline_assets_owned', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('guideline_max_weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notice_date', models.DateField()),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('traded_amount', models.FloatField()),
                ('traded_shares', models.FloatField()),
                ('trade_note', models.TextField()),
                ('breaches', models.TextField()),
                ('account_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Portfolio')),
                ('isin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('index_isin', models.CharField(max_length=200)),
                ('flag_cash', models.BooleanField(default=False)),
                ('value', models.FloatField()),
                ('shares', models.FloatField()),
                ('price', models.FloatField()),
                ('account_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Portfolio')),
                ('isin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='BBGData',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('assets', models.FloatField()),
                ('shares_issued', models.FloatField()),
                ('isin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Fund')),
            ],
        ),
    ]
