# Generated by Django 2.2.4 on 2019-08-12 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='valuation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
