# Generated by Django 2.2.4 on 2019-08-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_position_valuation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='index_isin',
        ),
    ]
